version: "3.8"

services:
  fungiclef:
    image: fungiclef-example:latest
    build: .
    container_name: fungiclef-example
    volumes:
    - /media/Data-10T-1/Data/DF21_300:/Data
    # settings related to nvcr.io/nvidia/pytorch:22.12-py3 docker image
    ipc: "host"
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "12g"
        reservations:
          devices:
            - capabilities: [ "gpu" ]
              driver: nvidia
              count: all
